### ISSUE TITLE
How could I build a ios library for  ios-tesseract  by myself?

### ISSUE THREAD

**Issue by magneter** [SwiftyTesseract/SwiftyTesseract#18]
First of all  ,It is a great job. thank you very muck.
I read the code ,but  I still cant find a way to rebuild a  " ios-tesseract" like this.
The tesseract  is updated frequency, so ...it is time for updating .
Could you submit a video or a wiki to explain the steps ,how to build a library like this.
many Thanks.

**Comment by magneter** [comment]
sometimes I want to modify the code in tesseract .Please.

**Comment by Steven0351** [comment]
I’m not against putting the makefile for compiling tesseract in the repo and making it available, but I have many other projects on my list and it’s frankly not a high priority for me because there are not people clamoring to make contributions to the project. Currently the way I build the binaries is kind of hacked together. I’ll be pushing an update that uses the latest release version of Tesseract in the next few days, but the Makefile I use is based on https://github.com/gali8/Tesseract-OCR-iOS/blob/master/TesseractOCR/Makefile.

**Comment by wacumov** [comment]
First of all, thank you for this awesome library. 
Do you plan to update the version of Tesseract in near future?

**Comment by Steven0351** [comment]
Makefile is now available in the repo
