### ISSUE TITLE
setTesseractVariable has no effect for .lstmOnly

### ISSUE THREAD

**Issue by wacumov** [SwiftyTesseract/SwiftyTesseract#22]
I found out a strange issue.

 `setTesseractVariable(.preserveInterwordSpaces, value: preserveInterwordSpaces ? "1" : "0")`

has no effect if `engineMode` is set to `.lstmOnly`. 

But setting `preserve_interword_spaces` parameter should has effect for Tesseract 4 since this commit -
https://github.com/tesseract-ocr/tesseract/commit/ea557a3e667b915bcc071ffb20484e7e4e7583ce 

Currently the library uses Tesseract 4.0.0beta-4 and that commit was pushed before beta-4 was released.
This [Tesseract-OCR-iOS fork](https://github.com/chaoskyme/Tesseract-OCR-iOS) also uses Tesseract 4. And setting `preserve_interword_spaces` works fine there. 

@Steven0351 do you have any thoughts what can be the cause?

**Comment by Steven0351** [comment]
Are you pulling in through Cocoapods? I haven’t cut the new release yet because I need to regenerate the docs so it includes your added feature.

**Comment by wacumov** [comment]
No, I use Carthage and my `Cartfile`contains a line
`github "SwiftyTesseract/SwiftyTesseract" "master"`
so, I have the freshest code.

**Comment by Steven0351** [comment]
Okay, I’ll update the libs tonight. I know that the whitelist and blacklist tesseract variables are only available for use in `tesseractOnly` mode, which could potentially be the case here as well

**Comment by Steven0351** [comment]
So, updating the libs didn't do much in regards to recognizing the multiple spaces that were being recognized using `EngineMode.tesseractOnly`, however I used another image with more exaggerated spacing and it preserved multiple spaces (albeit not 100% accurate) in `EngineMode.lstmOnly`. It could be related to the quality of the image, but it's hard to be 100% certain since OCR can be hit or miss on a single recognition attempt.

**Comment by wacumov** [comment]
Thank you very much for the update!
That's strange, but preserving multiple spaces in `.lstmOnly` works fine with *the same image* in Tesseract-OCR-iOS.
(I used this [repo](https://github.com/wacumov/Tesseract-OCR-4-iOS) for research)

**Comment by Steven0351** [comment]
Tesseract-OCR-iOS does image preprocessing before performing recognition on it, while SwiftyTesseract does no preprocessing on behalf of the user

**Comment by Steven0351** [comment]
Since this does seem to be fairly common and most people don’t want to spend a lot of time performing image optimizations, I’ll probably make some options at the SwiftyTesseract level in the next major version to allow for some sane default image processing options. I have image processing logic in SwiftyTesseractRTE but there seems to be enough of a need for it in this project that I may pull it into this project instead.

**Comment by wacumov** [comment]
It seems that Tesseract-OCR-iOS does not image preprocessing. It has an optional method in 
G8TesseractDelegate [protocol](https://github.com/wacumov/Tesseract-OCR-4-iOS/blob/master/TesseractOCR/G8TesseractDelegate.h).
And this method is not implemented in the demo project I used for research.
There are `g8_blackAndWhite` and `g8_grayScale` methods in a UIImage extension. But these methods are deprecated and are not used in current implementation.

About image processing in SwiftyTesseract - I think this library should not be responsible for image processing. I use [GPUImage](https://github.com/BradLarson/GPUImage2) for this task. It works faster than CoreImage. And the image with text can be prepared for OCR in three lines of code using GPUImage.

**Comment by Steven0351** [comment]
It does indeed do at least one preprocessing step. If you comb through the implementation, you’ll see that it uses a Leptonica function that does a lower level image processing before it is passed to the library. My additions would be optional and not enabled by default.
