### ISSUE TITLE
Swift 5 conversion

### ISSUE THREAD

**Issue by hunterteck** [SwiftyTesseract/SwiftyTesseract#31]
Hi there! Sorry for bothering you. When can we expect swift 5 conversion?

**Comment by Steven0351** [comment]
As much as I love the latest and greatest as everyone else, a Swift 5 conversion would mean bumping a major version with little benefit at this point. There are some public API facing changes that I've been kicking around in my head, and if I bumped a major version just for the sake of converting to Swift 5, then I would have to bump the major version _again_ when those changes were introduced. Swift 5 projects can depend on frameworks written in Swift 4 and 4.2 (excerpt from https://docs.swift.org/swift-book/GuidedTour/Compatibility.html):
> A target written in Swift 5 can depend on a target that’s written in Swift 4.2 or Swift 4, and vice versa. This means, if you have a large project that’s divided into multiple frameworks, you can migrate your code from Swift 4 to Swift 5 one framework at a time.

**Comment by shahidlatif2007** [comment]
Any update on this?

**Comment by qasimmajeed** [comment]
Any update regarding Swift 5 ?

**Comment by Steven0351** [comment]
A Swift 5 update will happen if a new feature is added, however I haven't been actively developing new features for this library for some time. I haven't personally used this project since Apple's Vision framework began performing OCR and have only been maintaining bug fixes and the occasional response to opened issues. Swift 5 projects can import Swift 4.2 frameworks so I'm not sure what the need is here.

You are more than welcome to open a pull request to add support for Swift 5.

**Comment by Steven0351** [comment]
Library has been updated to Swift 5.2
