### ISSUE TITLE
PDF OCR progress callback

### ISSUE THREAD

**Issue by JulianKahnert** [SwiftyTesseract/SwiftyTesseract#34]
Hi @Steven0351,
I thought it might be better to have this conversation about a progress feature here in a new issue.

As mentioned in #33 I was looking for some kind of progress monitor to get more information about the state of OCR processing. This tesseract API might be helpful:
```swift
let monitor = TessMonitorCreate()
let status = TessMonitorGetProgress(monitor)
TessMonitorDelete(monitor)
```

To answere your question about the API (in #33 ) ... I thought of a delegate, that will be called when changes in the processing happen, e.g.:
```swift
public protocol SwiftyTesseractDelegate: AnyObject {
    func swiftyTesseract(_ swiftyTesseract: SwiftyTesseract, didRecieveProgressChange progress: Double)
}
```

imho the progress might be a value between 0...1.0 which could be calculated as:
```swift
let numOfPages = 4.0
let completedPages = 1.0
let progressOfCurrentPage = 0.66

let totalProgress = (progressOfCurrentPage + completedPages)/numOfPages
```

This assumes that all pages take an equal amount of time to be calculated, but it might be a good approximation. What do you think?

**Comment by JulianKahnert** [comment]
Hi @Steven0351, are you still looking into this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Steven0351** [comment]
I am, but I haven’t made much progress yet. I recently moved so it’s a bit hectic in my personal life at the moment. 

I’m also trying to figure out what kind of place the library has now that Vision.framework does OCR starting in iOS 13.0. I did some benchmarking and comparisons when I found out about it, but I have yet to draw any conclusions. So far “fast” recognition in Vision blows SwiftyTesseract out of the water for speed, but “accurate” recognition is much slower. However, since it’s not supported in earlier versions I’ll still be supporting the library until at least iOS 14.0

**Comment by JulianKahnert** [comment]
Oh, that's funny. That's exactly how I feel. We have also moved.
Yes you're right, there are some cool changes in the new VisionKit. Unfortunately there is no possibility (at least I didn't find any) to create a PDF with text directly.

**Comment by Steven0351** [comment]
I've actually had time to spend more time on the project; are you still wanting the progress callback? I remember we were having issues in the last PR you had opened and you opted for the plain `performOCR` method instead of the PDF rendering.

**Comment by JulianKahnert** [comment]
Hi @Steven0351 
you are right! With the iOS 13 release of [PDF Archiver](https://pdf-archiver.io), I will switch to the SDK OCR framework, which was awesome in the tests. So I am not waiting for this feature anymore. It was a pleasure working with you on this project. 🙂
