### ISSUE TITLE
why do you not use default implementation.

### ISSUE THREAD

**Issue by masakih** [SwiftyTesseract/SwiftyTesseract#38]
Why do you not use automatic implementation of == operator of TesseractOption, and not use default implementation of subtracting(_:) of Set.

**Comment by Steven0351** [comment]
Hashable (and by extension Equatable) are given custom implementations because of how the Swift compiler synthesizes conformance for enums with associated types (it includes the associated type in how the hash is calculated). So, TesseractOptions of `.blackList(“1234”)` and `.blackList(“ABCD”)` would have two different hash values calculated. In 99.9% of cases this is the desired outcome. However, the Set<TesseractOption> should only have one of each type contained (e.g. there should not be two `TesseractOption.blackList`s, as it’s used to assign the underlying tesseract library variables. If you initialize SwiftyTesseract with `.blackList(“1234”)`, but in your logic sometime later you decide that it should be `.blackList(“ABCD”)`, without the custom implementation you would have both `.blackList`s in your Set and would lead to unpredictable behavior because Sets are unordered collections. 

The non-default `subtracting(_:)` is used because since two `TesseractOption`s make the same hash with the custom Hashable implementation, if you set a new value it wouldn’t be recognized by the default `subtracting(_:)` method and you’d end up with undesired results. The goal here is to not continuously set all the variables to Tesseract if they haven’t been changed.

All of that being said, you are referring to implementation details in a branch that is currently in active development and those implementation details or public facing API’s can and will change without warning. I may decide to wrap that Set in a type that makes the Set opaque to the end user, or if I find that setting the Tesseract variables every time if they are unchanged is more performant than my `subtracting` implementation I will remove it.

**Comment by Steven0351** [comment]
This is not regarding a bug or feature request, so I’m closing the issue

**Comment by masakih** [comment]
I understand.
Thank you for your detailed information.
