### ISSUE TITLE
Can we read  "Text + Any Emoji"

### ISSUE THREAD

**Issue by cmdr-surender-singh** [SwiftyTesseract/SwiftyTesseract#49]
Hello,
I want to read "text + emoji", but there is issue with emoji 
when I read this image it prints "This is for testing =\n"
Let me know if any one help 
attached Image which I want to recognise 
![testImg](https://user-images.githubusercontent.com/42886349/69477247-e0f70100-0e09-11ea-816e-a5cf6f9569ed.png)

**Comment by Steven0351** [comment]
I’m not sure this is possible for OCR in general since any platform can choose to render emoji however it wants to. Even if it is possible, this library is just a wrapper around [Tesseract](https://github.com/tesseract-ocr/tesseract) and that functionality would need to be introduced in that project before it could be possible in this one

**Comment by Steven0351** [comment]
It may be possible to [train Tesseract](https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract) to recognize Emoji yourself

**Comment by cmdr-surender-singh** [comment]
Thanks @Steven0351 will check **train tesseract**
