### ISSUE TITLE
SwiftyTesseract for MacOS APP

### ISSUE THREAD

**Issue by Buzka91** [SwiftyTesseract/SwiftyTesseract#63]
### Checklist
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).

**Is your feature request related to a problem? Please describe.**
I wanted try Tesseract for Swift but it appears that that its only for iOS apps.

**Describe the solution you'd like**
Im beginner at coding on apple devices (project of myself only) and i don't know if its possible to extend this wrapper to macOS apps? 

**Describe alternatives you've considered**
If its only for iOS, why not create new project for MacOS Apps?

**Additional context**
`[!] The platform of the target 'test-app' (macOS 10.15) is not compatible with 'SwiftyTesseract (3.1.2)', which does not support 'macOS'.`

**Comment by Steven0351** [comment]
I have no intention of supporting macOS. You're building against macOS 10.15, so you have access to first party OCR through https://developer.apple.com/documentation/vision/locating_and_displaying_recognized_text_on_a_document

**Comment by Steven0351** [comment]
I just read closer and I saw that you said you are a beginner. Historically macOS and iOS have not shared a common UI Framework. There is now a way to write UIKit apps for the Mac, however, I find this library to be of little use if you're already targeting macOS 10.15 or iOS 13.0 since those are the OS versions that Apple introduced their own OCR feature into the Vision framework. At this point in time, the only advantage this library has over what Apple has in the Vision framework is supporting versions of iOS < 13.0
