### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by JJAYCHEN1e** [SwiftyTesseract/SwiftyTesseract#65]
### Checklist
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).

**Is your feature request related to a problem? Please describe.**
I'm developing for Linux, but it seems CocoaPods and Carthage doesn't support Linux.

**Describe the solution you'd like**
Would you like to add **Swift Package Manager** support for SwiftyTesseract? It just works for Linux!

**Describe alternatives you've considered**
Is there any other method to add SwiftyTesseract to my project?  I noticed that you claimed using CocoaPods or Carthage are the only supported methods.

**Comment by Steven0351** [comment]
This library is incompatible with SPM at the moment until Swift 5.3 is available due to the fact the project vendors it’s static framework binaries dependencies (which is required for iOS). The library is also incompatible with Linux because it depends on UIKit to go from `UIImage -> Result<String, Error>`, so it would require a bit of a refactor to be platform agnostic.

**Comment by Steven0351** [comment]
Leave open

**Comment by Steven0351** [comment]
This has been implemented in the Swift 5.3 branch, but there is currently an issue with testing with SPM on macOS when using bundle resources.

**Comment by Steven0351** [comment]
#74 merges these changes into the develop branch to be merged into master and released as version 4.0.0 when the Xcode 12 GM is available.
