### ISSUE TITLE
M1 chip iOS simulator problem

### ISSUE THREAD

**Issue by nikolindima** [SwiftyTesseract/SwiftyTesseract#88]
Try to use SwiftyTesseract with M1 chip. have differnt errors try to run on simulator. if set Build Active Architecture Only to YES/NO

Showing Recent Messages
Ignoring file Library/Developer/Xcode/DerivedData/tesseractTest-euleoucgiaaolsdwlbftbdoqmqbl/Build/Products/Debug-iphonesimulator/libtesseract.framework/libtesseract, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

or 
Could not find module 'SwiftyTesseract' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**Versions**
* Xcode: 12.4
* Swift: 5.3 
* iOS: 14
* SwiftyTesseract: 4.0.0

**Comment by Steven0351** [comment]
This is an issue with SwiftyTesseract/libtesseract not being built with support for the M1. There is an [open issue there already](https://github.com/SwiftyTesseract/libtesseract/issues/4) that I’ve started working on since I have an M1 machine now. I have to redo the build to build fat binaries again for specific platforms so that the xcframework contains the correct arch slices for the platforms (e.g. arm64 and x86_64).
